services:
  server:
    build: ./server
    environment:
      PG_DB_URL: "postgres://postgres:pass@db:5432/todoctian?sslmode=disable"
    ports:
      - "5656:5656"
    depends_on:
      migrate:
        condition: service_completed_successfully
  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: todoctian
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://postgres:pass@db:5432/todoctian?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/migrations:/migrations
  postgres:
    image: postgres/16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
