// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	Name      string
}

type Task struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamp
	ParentTaskID pgtype.UUID
	ProjectID    pgtype.UUID
	Status       string
	Order        int32
	Name         string
}
